%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Copyright (c) 2024, Amon Lahr, Simon Muntwiler, Antoine Leeman & Fabian Flürenbrock Institute for Dynamic Systems and Control, ETH Zurich.
%
% All rights reserved.
%
% Please see the LICENSE file that has been included as part of this package.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function [H_u, h_u, H_x, h_x] = generate_constraints_cc(params)
        constraints = params.constraints;
        h_x = [constraints.T1Max; -constraints.T1Min; constraints.T2Max; -constraints.T2Min; constraints.T3Max; -constraints.T3Min];
        H_x = [ 1  0  0; ...
              -1  0  0; ...
               0  1  0; ...
               0 -1  0; ...
               0  0  1; ...
               0  0 -1];
        h_u = [constraints.P1Max; -constraints.P1Min; constraints.P2Max; -constraints.P2Min];
        H_u = [ 1  0; ...
              -1  0; ...
               0  1; ...
               0 -1];
end

